server:
  port: 9002

spring:
  application:
    name: CONTACT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/sample
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  config:
    import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}/suvankar

property: ${contact}
