server:
  port: 9004

spring:
  application:
    name: ITINERARY-SERVICE

  data:
    mongodb:
      uri: mongodb+srv://jvo55580:ankit@travel.3mrqbxo.mongodb.net/?retryWrites=true&w=majority
      database: itinerary_management

  cloud:
    consul:
      discovery:
        prefer-ip-address: true