server:
  port: 9002

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://sql12.freemysqlhosting.net:3306/sql12643291
    username: sql12643291
    password: 8xaMFiffRX
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  cloud:
    consul:
      discovery:
        prefer-ip-address: true
